---

systemUpgradeRequired: false

javaVersion: 8

useSystemFirewall: false

cassandraGroup: cassandra
cassandraUser: cassandra
cassandraGroupId: 5000
cassandraUserId: 5000

cassandraInstallDir: /opt
cassandraDataDir: /opt/cassandra-data
cassandraLogDir: /opt/cassandra-logs

cassandraAutoBootstrap: false
cassandraEndpointSnitch: GossipingPropertyFileSnitch # or SimpleSnitch
cassandraDc: dc1
cassandraRack: rack1

cassandraVersion: 3.11.2
downloadRegion: eu          # eu/us
cassandraUrl: "http://www-{{ downloadRegion }}.apache.org/dist/cassandra/{{ cassandraVersion }}/apache-cassandra-{{ cassandraVersion }}-bin.tar.gz"

cassandraPidDir: /var/run/cassandra
cassandraPidFile: "{{ cassandraPidDir }}/cassandra.pid"

cassandraClusterName: 116davinder
cassandraNumToken: 256

proxyEnv:
  http_proxy: ""
  https_proxy: ""