---

systemUpgradeRequired: false

javaVersion: 8
updateJava: false # only when you need to update java version

useSystemFirewall: false

cassandraGroup: cassandra
cassandraUser: cassandra
cassandraGroupId: 5000
cassandraUserId: 5000

cassandraInstallDir: /opt
cassandraDataDir: /opt/cassandra-data
cassandraLogDir: /opt/cassandra-logs

cassandraAutoSnapshot: true
cassandraIncrementalBackups: "{{ cassandraAutoSnapshot }}"     # set false if alternate way is there

cassandraEndpointSnitch: GossipingPropertyFileSnitch # or SimpleSnitch/Ec2MultiRegionSnitch/GossipingPropertyFileSnitch
cassandraDc: dc1
cassandraRack: rack1

cassandraXms: 512m
cassandraXmx: "{{ cassandraXms }}"
cassandraXmn: 64m
cassandraXss: 256k
cassandraRpcMinThreads: 4
cassandraRpcMaxThreads: 250
cassandraStoragePort: 7000
cassandraNativeTransportPort: 9042

cassandraVersion: 3.11.2
cassandraOldVersion: 3.11.1 # only used in cassandraRomveOldVersions.yml

downloadRegion: eu          # eu/us
cassandraUrl: "http://www-{{ downloadRegion }}.apache.org/dist/cassandra/{{ cassandraVersion }}/apache-cassandra-{{ cassandraVersion }}-bin.tar.gz"

cassandraPidDir: /var/run/cassandra
cassandraPidFile: "{{ cassandraPidDir }}/cassandra.pid"

cassandraClusterName: 116davinder
cassandraNumToken: 256

proxyEnv:
  http_proxy: ""
  https_proxy: ""