---

- name: decomission node from cluster
  command: "{{ cassandraNodeTool }} decommission"
  ignore_errors: true

# TODO: need more testing here
- name: status check for decomission node
  shell: "set -o pipefail && {{ cassandraNodeTool }} status | grep -w '{{ ansible_host }}'"
  changed_when: false
  register: decomissionNodeStatus
  failed_when: decomissionNodeStatus.rc == 0 
  until: decomissionNodeStatus.rc == 1
  retries: 30
  delay: 10

- name: Stoping cassandra service
  import_role:
    name: serviceState
  vars:
    serviceName: cassandra
    serviceState: stopped

- name: Cassandra Port Status
  include_role:
    name: portCheck
  vars:
    PortNumber: "{{ item }}"
    PortStatus: stopped
  loop:
    - "{{ cassandraStoragePort }}"
    - "{{ cassandraNativeTransportPort }}"

- name: Removing all installation files
  command: "/bin/rm -rf {{ cassandraInstallDir }}/apache-cassandra-*"

- name: Removing data & log dirs related to installation
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ cassandraInstallDir }}/cassandra"
    - "{{ cassandraDataDir }}"
    - "{{ cassandraLogDir }}"