---

- hosts: clusterNodes
  gather_facts: true
  pre_tasks:
  
    - name: Including system upgrade role
      import_role:
        name: systemUpgrade
      when: systemUpgradeRequired

    - name: Including java role
      import_role:
        name: java

  roles:
    - common
    - install
    - configure
    - service