---

- hosts: clusterSeedNodes:clusterNodes:clusterAddNodes
  gather_facts: true
  serial: 1
  tasks:
    - name: including restart tasks
      import_role:
        name: serviceState
      vars:
        serviceName: cassandra
        serviceState: restarted

    - name: Cassandra Port Status
      include_role:
        name: portCheck
      vars:
        PortNumber: "{{ item }}"
        PortStatus: started
      loop:
        - "{{ cassandraStoragePort }}"
        - "{{ cassandraNativeTransportPort }}"