---

- hosts: clusterNodes:clusterSeedNodes:clusterAddNodes
  gather_facts: false
  tasks:
    - name: Removing Old Cassandra files | {{ cassandraInstallDir }}/apache-cassandra-{{ cassandraOldVersion }}
      file:
        path: "{{ cassandraInstallDir }}/apache-cassandra-{{ cassandraOldVersion }}"
        state: absent
      when:
        - cassandraOldVersion
        - cassandraOldVersion != cassandraVersion