---

- hosts: clusterSeedNodes:clusterNodes
  gather_facts: true
  serial: 1
  tasks:
    - name: including restart tasks
      import_role:
        name: service
        tasks_from: cassandraState
      vars:
        cassandraServiceName: cassandra
        cassandraState: restarted

    - name: Cassandra Port Status
      include_role:
        name: portCheck
      vars:
        PortNumber: "{{ item }}"
        PortStatus: started
      loop:
        - "{{ cassandraStoragePort }}"
        - "{{ cassandraNativeTransportPort }}"