---

- hosts: clusterNodes:clusterSeedNodes:clusterAddNodes
  gather_facts: true
  serial: 1
  tasks:
    - include_role:
        name: configure
        tasks_from: dynamicConfigs
      vars:
        - cassandraConfigFile: logback.xml
  
    - name: Restarting all nodes
      import_role:
        name: serviceState
      vars:
        serviceName: cassandra
        serviceState: restarted
      when: configStatus.changed

    - name: Cassandra Port Status
      include_role:
        name: portCheck
      vars:
        PortNumber: "{{ item }}"
        PortStatus: started
      loop:
        - "{{ cassandraStoragePort }}"
        - "{{ cassandraNativeTransportPort }}"
      when: configStatus.changed