---

- hosts: localhost
  gather_facts: false
  become: false
  roles:
    - initialClusterChecks

- hosts: clusterNodes:clusterSeedNodes
  gather_facts: true
  pre_tasks:
    - name: Including system upgrade role if required
      import_role:
        name: systemUpgrade
      when: systemUpgradeRequired

    - name: Including java upgrade role if required
      import_role:
        name: java

  roles:
    - common
    - install
    - configure
    - service

- hosts: clusterSeedNodes:clusterNodes
  gather_facts: false
  serial: 1
  tasks:
    - name: Restarting all seed nodes and then other nodes
      import_role:
        name: serviceState
      vars:
        serviceName: cassandra
        serviceState: restarted

    - name: Cassandra Port Status
      include_role:
        name: portCheck
      vars:
        PortNumber: "{{ item }}"
        PortStatus: started
      loop:
        - "{{ cassandraStoragePort }}"
        - "{{ cassandraNativeTransportPort }}"