---

- hosts: clusterAddNodes
  gather_facts: true
  serial: 1
  pre_tasks:
    - name: Including system upgrade role
      import_role:
        name: systemUpgrade
      when: systemUpgradeRequired

    - name: Including java role
      import_role:
        name: java

  roles:
    - common
    - install
    - configure
    - service

  post_tasks:
    - name: Starting all additional nodes
      import_role:
        name: service
        tasks_from: cassandraState
      vars:
        cassandraServiceName: cassandra
        cassandraState: started

    - name: Cassandra Port Status
      include_role:
        name: portCheck
      vars:
        PortNumber: "{{ item }}"
        PortStatus: started
      loop:
        - "{{ cassandraStoragePort }}"
        - "{{ cassandraNativeTransportPort }}"