---

- hosts: clusterNodes
  gather_facts: true
  pre_tasks:
    - import_role:
        name: systemUpgrade
      when: systemUpgradeRequired

    - import_role:
        name: java

  roles:
    - common
    - install
    - configure
    - service