---

- name: Install Openjdk | {{ javaVersion }} | RedHat
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "java-1.{{ javaVersion }}.0-openjdk"
    - "java-1.{{ javaVersion }}.0-openjdk-devel"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Openjdk | {{ javaVersion }} | Debian
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "openjdk-{{ javaVersion }}-jdk"
    - "openjdk-{{ javaVersion }}-jre"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'