---

- name: Getting Java Home Path from System
  shell: "readlink -fsq $(which java) | sed 's:/jre/bin/java::'"
  register: javaHomeLocation

- name: Setting Java Home | /etc/profile.d/java.sh
  blockinfile:
    path: /etc/profile.d/java.sh
    mode: 0775
    group: root
    owner: root
    create: true
    block: |
      export JAVA_HOME={{ javaHomeLocation.stdout }}
      export PATH=$PATH:{{ javaHomeLocation.stdout }}/bin