---
- name: Creating cassandra configurations | {{ cassandraConfigFile }}
  template:
    src: "{{ cassandraConfigFile }}"
    dest: "{{ cassandraInstallDir }}/cassandra/conf/{{ cassandraConfigFile }}"