---

- name: Creating cassandra configurations
  include_role:
      name: configure
      tasks_from: dynamicConfigs.yml
  vars:
    - cassandraConfigFile: "{{ item }}"
  loop:
    - cassandra-rackdc.properties
    - cassandra-topology.properties
    - cassandra.yaml
    - jvm.options
    - logback.xml