---

- name: creating a cassandra auto repair cron file under /etc/cron.d
  cron:
    name: cassandra auto repair
    minute: *
    hour: *
    day: *
    month: *
    weekday: "{{ 6 | random(seed=inventory_hostname) }}" # default gc_grace_period is 10 days
    user: root
    job: "{{ cassandraInstallDir }}/cassandra/bin/nodetool repair -full -local -seq"
    cron_file: cassandra_auto_repair