---
- name: Download cassandra
  include_tasks: download.yml

- name: Create cassandra dir symlink
  include_tasks: createSymlink.yml

- name: Setting cassandra version into profile.d
  include_tasks: envSet.yml